### ISSUE TITLE
Would ketcher support the folded render style of superatoms?

### ISSUE THREAD

**Issue by ClinuxMDL** [ggasoftware/ketcher#3]
Hello developers,

Would ketcher support the folded render style of superatoms? like the following picture

![image](https://user-images.githubusercontent.com/13743363/135304424-94d86aaf-71c3-4ded-bd7b-1c274b6d7699.png)

If this toolkit has this feature, let me know how to call it. Thanks

**Comment by mkviatkovskii** [comment]
Dear @ClinuxMDL,
This repository is archived, please open your ticket in https://github.com/epam/ketcher.
